name: Build AndroidAPS APK

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      run: |
        echo "Installing Android SDK..."
        sdkmanager --install "platforms;android-33" "build-tools;33.0.2" "ndk;23.1.7779620"

    - name: Grant execute permission
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: AndroidAPS-APK
        path: app/build/outputs/apk/release/app-release.apk
